#!/usr/bin/env bash
# Demo script showing what the analyzers would detect in spez's Reddit comments
# This simulates the integration test without needing actual Reddit API credentials

set -e

echo "=================================="
echo "DIGITAL HISTORY ANALYZER DEMO"
echo "Simulating analysis of u/spez"
echo "=================================="
echo ""

# Simulate scanning
echo "[INFO] Scanning Reddit user: spez"
echo "[INFO] Collected 100 posts"
echo "[INFO] Collected 500 comments"
echo ""

# Simulate analyzer runs
echo "[INFO] Running political content analyzer..."
sleep 1
echo "  ✓ Analyzing posts for political keywords..."
echo "  ✓ Analyzing comments for political keywords..."
echo "  ✓ Checking subreddit participation..."
echo ""

echo "[INFO] Running NSFW content analyzer..."
sleep 1
echo "  ✓ Scanning for NSFW subreddits..."
echo "  ✓ Checking for thirst trap keywords..."
echo ""

echo "[INFO] Running PII/slur analyzer..."
sleep 1
echo "  ✓ Detecting personal information..."
echo "  ✓ Scanning for offensive language..."
echo ""

# Simulated results
echo "=================================="
echo "ANALYSIS COMPLETE"
echo "=================================="
echo ""
echo "Total findings: 127"
echo ""
echo "Breakdown by category:"
echo "  Political:  89 findings (medium severity)"
echo "  NSFW:       12 findings (medium severity)"
echo "  PII:        18 findings (high severity)"
echo "  Slurs:      8 findings (high severity)"
echo ""

echo "=================================="
echo "SAMPLE POLITICAL FINDINGS"
echo "=================================="
echo ""
echo "1. [comment:abc123] Political keyword detected: reddit"
echo "   Subreddit: r/announcements"
echo "   Matched text: 'reddit'"
echo "   Context: Discussion about Reddit policy changes"
echo ""
echo "2. [comment:def456] Posted in political subreddit"
echo "   Subreddit: r/ModSupport"
echo "   Description: Comment in moderation policy discussion"
echo ""
echo "3. [comment:ghi789] Political keyword detected: administration"
echo "   Subreddit: r/modnews"
echo "   Matched text: 'administration'"
echo "   Context: Reddit administration update"
echo ""
echo "4. [post:jkl012] Political keyword detected: policy"
echo "   Subreddit: r/announcements"
echo "   Title: New community policy guidelines"
echo ""
echo "5. [comment:mno345] Political keyword detected: government"
echo "   Subreddit: r/technology"
echo "   Context: Discussion about tech regulation"
echo ""

echo "=================================="
echo "SAMPLE NSFW FINDINGS"
echo "=================================="
echo ""
echo "1. [comment:pqr678] Commented in NSFW subreddit"
echo "   Subreddit: r/NSFW411"
echo "   Description: Moderation-related comment (spez moderates many subs)"
echo ""
echo "2. [comment:stu901] Commented in NSFW subreddit"
echo "   Subreddit: r/nsfw"
echo "   Description: Policy announcement about NSFW content"
echo ""

echo "=================================="
echo "SAMPLE PII FINDINGS"
echo "=================================="
echo ""
echo "1. [comment:vwx234] PII detected: email"
echo "   Matched text: [REDACTED]@reddit.com"
echo "   Severity: HIGH"
echo "   Recommendation: DELETE"
echo ""
echo "2. [comment:yza567] PII detected: ip_address"
echo "   Matched text: 192.168.x.x"
echo "   Severity: MEDIUM"
echo "   Recommendation: REVIEW"
echo ""

echo "=================================="
echo "RECOMMENDATIONS"
echo "=================================="
echo ""
echo "HIGH PRIORITY (26 items):"
echo "  - 18 PII detections → DELETE immediately"
echo "  - 8 slur detections → DELETE for professional image"
echo ""
echo "MEDIUM PRIORITY (101 items):"
echo "  - 89 political content → REVIEW if reducing political footprint"
echo "  - 12 NSFW participation → REVIEW for professional cleanup"
echo ""
echo "Next steps:"
echo "  1. Run: digital-history review --username spez --category pii"
echo "  2. Run: digital-history cleanup --dry-run --category pii"
echo "  3. After review: digital-history cleanup --confirm --category pii"
echo ""

echo "=================================="
echo "DEMO COMPLETE"
echo "=================================="
echo ""
echo "To run this for real:"
echo "  1. Set Reddit API credentials (see docs/INTEGRATION_TESTING.md)"
echo "  2. Run: go test -v ./internal/analyzer/ -run TestIntegration_AnalyzeRedditUser"
echo ""
